name: webapp
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.4.6
  beamer: ^1.5.6
  flutter_hooks: ^0.20.3
  flutter_portal: ^1.1.4
  google_fonts: ^6.1.0
  glass: ^1.0.2+1
  graphql_flutter: ^5.2.0-beta.6
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  flutter_quill: ^8.5.4
  quill_delta: ^3.0.0-nullsafety.2
  firebase_core: ^2.22.0
  onesignal_flutter: ^3.5.1
  permission_handler: ^11.0.1
  firebase_analytics: ^10.7.0
  url_launcher: ^6.2.1
  fluttertoast: ^8.2.4
  flutter_html: ^3.0.0-beta.2
  flutter_svg: ^2.0.9
  path_provider: ^2.1.1
  flutter_pdfview: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
